### ISSUE TITLE
Missing lib libiconv.dll in the windows 64-bit installer 

### ISSUE THREAD

**Issue by philippeko** [zorba-processor/zorba#1]
Issue raised while running a simple example `zorba -q 1+1` in the **Zorba Command-line Client**

Following already tried to reinstall the package installer
NB: also please note that this package seems to be 32-bit as it was installed in the x86 directory

![image](https://cloud.githubusercontent.com/assets/78931/19077256/2715aa82-8a4c-11e6-8750-b67df3a2169a.png)

**Comment by devgc** [comment]
Also having issues with the Windows x64 installer.

After running the installer from https://github.com/zorba-processor/zorba/releases/download/4.0/zorba-3.0.0-win64-x64.exe.

I append path to python and import but I get error.

```
import sys
sys.path.append('C:\\Program Files (x86)\\Zorba XQuery Processor 3.0.0\\share\\python')
import zorba_api
print(u'end')
```

Here is the error
```
Traceback (most recent call last):
  File "D:\developement\ZorbaExamples\example1.py", line 3, in <module>
    import zorba_api
  File "C:\Program Files (x86)\Zorba XQuery Processor 3.0.0\share\python\zorba_api.py", line 26, in <module>
    _zorba_api = swig_import_helper()
  File "C:\Program Files (x86)\Zorba XQuery Processor 3.0.0\share\python\zorba_api.py", line 22, in swig_import_helper
    _mod = imp.load_module('_zorba_api', fp, pathname, description)
ImportError: DLL load failed: The specified module could not be found.
```

Also tried placing the pyd in in the Python DLL folder, still cant find it.

Not sure if it matters or not, but here is my Python version: Python 2.7.10 [MSC v.1500 64 bit (AMD64)] on win32

**Comment by devgc** [comment]
Also having issue with this. Would be great if you could recompile 64-bit installer with the libiconv.dll.

**Comment by devgc** [comment]
This seems to fix the issue:
https://groups.google.com/forum/#!topic/zorba-users/gVILIjduuuE

**Comment by shahsk0901** [comment]
navigate to the bin directory of zorba installation and rename the iconv.dll -> libiconv.dll
works just fine
